--Kurs Sorgularý
--Select * From TBLOGRENCILER where OGRSEHIR='Adana' or OGRKULUP='Satranç'



--Decimal(x,y)

--x: Virgülden Önce Basamak Sayýsý

--y: Virgülden Sonra Basamak Sayýsý

--Ortalama: 78,65 ** 100,00

--Decimal(5,2)



--SELECT * FROM TBLNOTLAR

--SELECT (SINAV1+SINAV2+SINAV3)/3 FROM TBLNOTLAR



--Insert Into TBLOGRENCILER (OGRAD,OGRSOYAD,OGRSEHIR) Values ('Baran','Yücedað','Elazýð')

--Select * From TBLOGRENCILER



--Insert Into TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV3) values (6,2,88,67)



--Delete From TBLDERSLER where DERSAD='Algoritma'



--Truncate Table TBLDERSLER



--Update TBLOGRENCILER Set OGRCINSIYET='Kýz' where OGRID=4 or OGRID=5



--Update TBLOGRENCILER set OGRKULUP='Kitaplýk' where OGRAD='Baran'



--Update TBLNOTLAR set DERS=2



--Insert Into TBLNOTLAR (OGRENCI,Ders,Sýnav1,Sýnav2) VAlues (5,2,78,66)

--Update TBLNOTLAR set ORTALAMA=(Sýnav1+Sýnav2+Sýnav3)/3

--Update Tblnotlar set durum=1 where ortalama>=50



--Select Count(*) As 'Toplam Kayýt' From TBLOGRENCILER

--Select Count(*) As 'Toplam Kiþi' From TBLOGRENCILER Where OGRSEHIR='Adana'



--Select Sum(SInav1),Sum(Sýnav2),Sum(Sýnav3) From TBLNOTLAR

--Select Avg(Sýnav1),Avg(Sýnav2),Avg(Sýnav3) From TBLNOTLAR

--Select Max(Sýnav1),Max(Sýnav2),Max(Sýnav3) From TBLNOTLAR

--Select Min(Sýnav1),Min(Sýnav2),Min(Sýnav3) From TBLNOTLAR



--Select OGRSEHIR,Count(*) as 'Toplam ' From TBLOGRENCILER GROUP BY OGRSEHIR



--Select OGRCINSIYET,COUNT(*) AS 'TOPLAM' FROM TBLOGRENCILER GROUP BY OGRCINSIYET



--Select OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP



--Select OGRSEHIR,COUNT(*) AS 'SAYI' FROM TBLOGRENCILER GROUP BY OGRSEHIR HAVING COUNT(*)=2



--SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP HAVING OGRKULUP='Kitaplýk'



--Select * From TBLOGRENCILER where OGRAD Like '%a%' or OGRSOYAD like '%a%'



--Select * From TBLOGRENCILER where OGRAD like 'a%' and OGRCINSIYET='erkek'



--Select * From TBLOGRENCILER where OGRAD like 'a%' and OGRCINSIYET='kýz'



--Select * From TBLOGRENCILER where OGRSEHIR like '%a%'



--select * from TBLOGRENCILER where OGRKULUP not like 'b%'



--Distinct



--Select DISTINCT OGRSEHIR FROM TBLOGRENCILER

--SELECT COUNT(DISTINCT(OGRSEHIR)) FROM TBLOGRENCILER



--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER

--SELECT COUNT(DISTINCT(OGRKULUP)) AS 'KULÜP SAYISI' FROM TBLOGRENCILER



--Select * From TBLOGRENCILER order by OGRSEHIR



--SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER ORDER BY OGRKULUP DESC



---SELECT top 60 percent * FROM TBLOGRENCILER



--Select * From TBLOGRENCILER where OGRSEHIR like '%an_%'



--select * from TBLOGRENCILER where OGRAD like '%[N,I]'



---Select * From TBLOGRENCILER where OGRKULUP like '%[k-m]'



--Select top 4 * From TBLOGRENCILER order by ogrýd desc



--Select top 81 percent * from TBLOGRENCILER



--Select * from TBLOGRENCILER where OGRSEHIR='Ýzmir' or OGRSEHIR='Ankara' or OGRSEHIR='Adana'

--Select * From TBLOGRENCILER where OGRSEHIR in('Ýzmir','Ankara','Adana')



--Select * From TBLNOTLAR where sýnav1 not in(70,75,80,85,90)



--select * from TBLNotlar where ORTALAMA between 74 and 100



--Select * from TBLOGRENCILER where OGRAD not between 'A' And 'N'



--Update TBLOGRENCILER Set OGRKULUP=4 where OGRKULUP='Gezi'



--insert into TBLOGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) values ('Berna',4,'Ankara')



--Select NOTID,OGRAD + ' ' +OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM

--From TblNotlar

--INNER JOIN TBLDERSLER

--ON TBLNOTLAR.DERS=TBLDERSLER.DERSID

--INNER JOIN TBLOGRENCILER

--ON TBLNOTLAR.OGRENCI=TBLOGRENCILER.OGRID



--SELECT * FROM TBLNOTLAR



--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1



--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA<50



--DERSLER TABLOSUNDA ÝSMÝ MATEMATÝK OLAN DERSE AÝT SINAV NOT BÝLGÝSÝ

--SUB QUERY



--SELECT * FROM TBLNOTLAR WHERE DERS=(SELECT DERSID FROM TBLDERSLER WHERE DERSAD='MATEMATÝK')



--Select * FROM TBLNOTLAR

--Full JOIN TBLOGRENCILER

--ON TBLOGRENCILER.OGRID=TBLNOTLAR.OGRENCI



--Select * From TBLDERSLER Union Select * From TBLKULUPLER



--Select 20+4 As 'Toplam', 20-4 as 'Fark', 20*4 as 'Çarpým', 20/4 as 'Bölüm'



--Select * From TBLNOTLAR where Ders=1

--Update Tblnotlar Set SINAV2=Sýnav2+10 From TBLNOTLAR where Ders=1

--update tblnotlar set sýnav2=100 where sýnav2>100

--Select * From Tblnotlar where Ders=1

--Select Avg(Ortalama) From Tblnotlar where Ders=1

--Sýnýf ortalamasýnýn altýnda olan öðrencilerin "Durum2" sütunlarýnýn yanýna "Altýnda",aksi durumda

--üstünde yazdýran sorguyu hazýrlayýn...





--SELECT * FROM TBLNOTLAR



--ABS

--SELECT ABS(-85) AS 'MUTLAK'

--SELECT POWER(2,4) AS 'ÜS ALMA'



--SELECT POWER(SINAV1,2) FROM TBLNOTLAR



--SELECT SQRT(786) AS 'KAREKÖK'



--SELECT FLOOR(4.86) AS 'TABAN', CEILING(4.86) AS 'TAVAN'



--SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1

--SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

--SELECT SUM(SINAV1),AVG(SINAV1) FROM TBLNOTLAR INNER JOIN TBLDERSLER

--ON TBLNOTLAR.DERS=TBLDERSLER.DERSID

--WHERE OGRENCI=(SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='AYÞE' AND OGRSOYAD='ÇINAR')



--SELECT UPPER('merhaba') as 'Sütun'



--Select upper(OGRAD) as 'ÖÐRENCÝ ADI', upper(OGRSOYAD) AS 'SOYAD',

--LOWER(OGRSEHIR) AS 'ÞEHÝR'

--FROM TBLOGRENCILER



--SELECT SUBSTRING(OGRAD,1,1) + '.'+ OGRSOYAD AS 'AD SOYAD',OGRKULUP FROM TBLOGRENCILER



--SELECT LEFT('MERHABA DÜNYA',9),RIGHT('MERHABA ÝSTANBUL',2)

--SELECT LEFT(OGRAD,1) +'.' + OGRSOYAD AS 'Ad Soyad' FROM TBLOGRENCILER



--SELECT LEFT(DERSAD,3),AVG(ORTALAMA) FROM TBLNOTLAR

--INNER JOIN TBLDERSLER

--ON TBLDERSLER.DERSID=TBLNOTLAR.DERS

--GROUP BY DERSAD



--Select Len('Merhaba')

--Select ograd,len(Ograd),ogrkulup From TBLOGRENCILER where OGRSEHIR='Adana' and

--ogrkulup=(select kulupýd from TBLKULUPLER where KULUPAD='Biliþim')



--Select  * From TBLOGRENCILER where len(ograd)=4 or len(ograd)=3



--Select  rtrim('          Korkma Sönmez Bu Þafaklarda Yüzen Al Sancak       ')



--Select Replace('Murat Yücedað','Yücedað','Y.dað')



--Select replace('Merhaba bugün hava soðuk','ü','u')

--1.Parametre Ana Kelime Cümle

--2.Parametre Bulunacak Deðer

--3.Parametre Yeni Deðer



--Select CHARINDEX('e','SQL Derslerine Devam Ediyoruz',20)

--select len('SQL Derslerine Devam Ediyoruz')



--select charindex('a',ograd) from TBLOGRENCILER



--Select reverse('Murat')



--Select Reverse(DersAd) From TBLDERSLER



--create database SatisVT



--use SatisVT

--Create Table TBLKATEGORI

--(

--KATEGORIID tinyint identity(1,1) primary key,

--KATEGORIAD varchar(50)

--)



--Create Table TBLURUNLER

--(

--URUNID int identity(1,1) primary key,

--URUNAD varchar(50),

--URUNMARKA VARCHAR(50),

--KATEGORI tinyint,

--URUNALISFIYAT decimal(18,2),

--URUNSATISFIYAT decimal(18,2),

--URUNSTOK smallint check(URUNSTOK>0),

--URUNDURUM bit default '1'

--)



--CREATE TABLE TBLPERSONEL

--(

--PERSONELID smallint identity(1,1) primary key,

--PERSONELADSOYAD VARCHAR(50)

--)



--CREATE TABLE TBLMUSTERI

--(

--MUSTERIID int primary key identity(1,1),

--MUSTERIAD VARCHAR(50),

--MUSTERISOYAD VARCHAR(50),

--MUSTERISEHIR VARCHAR(13),

--MUSTERIBAKIYE DECIMAL(18,2)

--)



--CREATE TABLE TBLHAREKET

--(

--HAREKETID int primary key identity(1,1),

--URUN int,

--MUSTERI int,

--PERSONEL smallint,

--ADET int,

--TUTAR DECIMAL(18,2),

--TARIH SMALLDATETIME

--)



--TRUNCATE TABLE TBLURUNLER



--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BÝLGÝSAYAR')



--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EÞYA')



--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')



--INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')



--INSERT INTO TBLURUNLER (URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK)

--VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)



--SELECT * FROM TBLURUNLER



--UPDATE TBLURUNLER SET URUNAD='SU ISITICI' WHERE URUNAD='KETTLE'



--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM ÜRÜN' FROM TBLURUNLER INNER JOIN TBLKATEGORI

--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID GROUP BY KATEGORIAD ORDER BY COUNT(*)



--KATEGORÝ ADI BÝLGÝSAYAR OLAN ÜRÜNLERÝ SATIÞ FÝYATINA 500 TL ZAM YAPALIM...



--UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI

--WHERE KATEGORIAD='BÝLGÝSAYAR')

--SELECT * FROM TBLURUNLER



--SELECT COUNT(*) AS 'KAÇ FARKLI ÜRÜN',SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER



--SELECT * FROM TBLURUNLER



--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,

--(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR',

--(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR'

--FROM TBLURUNLER INNER JOIN TBLKATEGORI

--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID



--CREATE PROCEDURE HAREKETLER

--AS

--SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'AD SOYAD',

--PERSONELADSOYAD,ADET,TUTAR,TARIH

--FROM TBLHAREKET INNER JOIN TBLURUNLER

--ON TBLHAREKET.URUN=TBLURUNLER.URUNID

--INNER JOIN TBLMUSTERI

--ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID

--INNER JOIN TBLPERSONEL

--ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID



--EXECUTE HAREKETLER



--Create Procedure DENEME

--AS

--SELECT * FROM TBLURUNLER WHERE URUNSTOK>10



--EXEC DENEME



--DROP PROCEDURE DENEME



--ALTER PROCEDURE [dbo].[HAREKETLER]

--AS

--SELECT HAREKETID,URUNAD, LEFT(MUSTERIAD,1) + '.' + MUSTERISOYAD AS 'AD SOYAD',

--PERSONELADSOYAD,ADET,TUTAR,TARIH

--FROM TBLHAREKET INNER JOIN TBLURUNLER

--ON TBLHAREKET.URUN=TBLURUNLER.URUNID

--INNER JOIN TBLMUSTERI

--ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID

--INNER JOIN TBLPERSONEL

--ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

--EXEC HAREKETLER



--ALTER Procedure URUNGETIR

--@Deger varchar(50)='BUZDOLABI'

--as

--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER

--where URUNAD=@Deger



--EXECUTE URUNGETIR @Deger='Laptop'



--SELECT CURRENT_TIMESTAMP ANLIK TARÝH VE SAAT

--SELECT GETDATE()

--SELECT DATEPART(YEAR,GETDATE()), DATEPART(MONTH,GETDATE()),

--DATEPART(DAY,GETDATE())

--SELECT DATEPART(WEEK,GETDATE()), DATEPART(WEEK,'2019-05-20')



--SELECT DATEPART(QUARTER,'2019-05-20')



--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 3 AND 5 AND MUSTERI=1



--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND

--MUSTERI=(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ANKARA')



--USE SatisVT

--SELECT DATENAME(MONTH,getdate()),datename(MONTH,'2019.01.15')

--SELECT DATENAME(WEEKDAY,GETDATE())

--SELECT DATENAME(WEEKDAY,'2019.06.10')



--SELECT DATEDIFF(YEAR,'2010.10.25',GETDATE())

--SELECT DATEDIFF(MONTH,'2010.06.14','2015.08.06')

--SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBLHAREKET WHERE HAREKETID=1



--SELECT DATEADD(YEAR,3,'2009-10-25')

--SELECT DATEADD(DAY,45,GETDATE())

--SELECT DATEADD(MONTH,350,GETDATE())



--SELECT URUNAD,COUNT(*) AS 'ÜRÜN AD' FROM TBLHAREKET

--INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID

--GROUP BY URUNAD ORDER BY COUNT(*) ASC



--SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE

--KATEGORI=1)



--SELECT * FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI

--WHERE MUSTERISEHIR='ADANA')



--SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE

--KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))



--SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI

--WHERE MUSTERISEHIR='ADANA' OR MUSTERISEHIR='ANKARA')



--SELECT * FROM TBLHAREKET WHERE URUN=1



--UPDATE TBLURUNLER SET URUNSTOK=URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE

--URUN=10) WHERE URUNID=10



--CREATE TABLE KASA

--(

--TOPLAM decimal(18,2)

--)



--INSERT INTO TBLKASA VALUES (0)

--SELECT * FROM TBLKASA

--UPDATE TBLKASA SET TOPLAM=(SELECT SUM(TUTAR) FROM TBLHAREKET)



--CREATE TABLE TBLSAYAC

--(

--ISLEM int

--)



--INSERT INTO TBLSAYAC VALUES (0)



--UPDATE TBLSAYAC SET ISLEM=(SELECT COUNT(*) FROM TBLHAREKET)



--CREATE TRIGGER ISLEMARTIS

--ON TBLHAREKET

--AFTER INSERT

--AS

--UPDATE TBLSAYAC SET ISLEM=ISLEM+1



--CREATE TABLE TBLTOPLAMKATEGORI

--(

--ADET tinyint

--)



--UPDATE TBLTOPLAMKATEGORI SET ADET=(SELECT COUNT(*) FROM TBLKATEGORI)



--CREATE TRIGGER KATEGORIARTIS

--ON TBLKATEGORI

--AFTER INSERT

--AS

--UPDATE TBLTOPLAMKATEGORI SET ADET+=1



--CREATE TRIGGER KATEGORIAZALIS

--ON TBLKATEGORI

--AFTER DELETE

--AS

--UPDATE TBLTOPLAMKATEGORI SET ADET-=1



--CREATE VIEW TEST1

--AS

--SELECT * FROM TBLKATEGORI



--SELECT * FROM TEST1

--ALTER VIEW TEST1

--AS

--SELECT * FROM TBLKATEGORI WHERE KATEGORIID<4



--SELECT * FROM TEST1



--SELECT * FROM TEST2



--SELECT * FROM TEST3

